// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbMqu7jtDu0Shk9DKQi27fKervNbsBmA8',
    appId: '1:520430100737:web:18663d68d915e31ee97b00',
    messagingSenderId: '520430100737',
    projectId: 'gvinum-travel',
    authDomain: 'gvinum-travel.firebaseapp.com',
    storageBucket: 'gvinum-travel.firebasestorage.app',
    measurementId: 'G-RPR77YWQCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAci3EBCq8w3-ox3sm5J2dsn4nj6chu4BM',
    appId: '1:520430100737:android:45b2c80c5e5b9cb5e97b00',
    messagingSenderId: '520430100737',
    projectId: 'gvinum-travel',
    storageBucket: 'gvinum-travel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHs0JY5LSsGLGRvL_QOEwWyz9pWs8Nvp8',
    appId: '1:520430100737:ios:ea64730a4db93a87e97b00',
    messagingSenderId: '520430100737',
    projectId: 'gvinum-travel',
    storageBucket: 'gvinum-travel.firebasestorage.app',
    iosBundleId: 'com.example.gvinumTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHs0JY5LSsGLGRvL_QOEwWyz9pWs8Nvp8',
    appId: '1:520430100737:ios:ea64730a4db93a87e97b00',
    messagingSenderId: '520430100737',
    projectId: 'gvinum-travel',
    storageBucket: 'gvinum-travel.firebasestorage.app',
    iosBundleId: 'com.example.gvinumTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbMqu7jtDu0Shk9DKQi27fKervNbsBmA8',
    appId: '1:520430100737:web:ff2bc3fff8c3146ce97b00',
    messagingSenderId: '520430100737',
    projectId: 'gvinum-travel',
    authDomain: 'gvinum-travel.firebaseapp.com',
    storageBucket: 'gvinum-travel.firebasestorage.app',
    measurementId: 'G-ZP3TG5P9EM',
  );
}
